from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path("user-activity/", user_activity_view, name="user_activity_view"),
    path("user-search/api/", user_search_api, name="user_search_api"),
    path('users-management/', users_view, name='users-management'),
    path("users/<int:user_id>/gdpr/download/", gdpr_export_download, name="gdpr-export-download"),
    path("users/<int:user_id>/gdpr/email/", gdpr_export_email, name="gdpr-export-email"),
    path('ads-management/', ads_view, name='ads-management'),
    path('feature-toggles-management/', feature_toggles_view, name='feature-toggles-management'),
    path('login/', custom_login, name='admin-login'),
    path('permission-denied/', permission_denied, name='permission-denied'),
    path('edit-user/<int:user_id>/', edit_user, name='edit-user'),
    path('update-user/<int:user_id>/', update_user, name='update-user'),
    path('delete-user/<int:user_id>/', delete_user, name='delete-user'),
    path('ban-user/<int:user_id>/', ban_user, name='ban-user'),
    path('live-activity/', live_activity_view, name='live_activity'),
    path('live-activity/api/', live_activity_api, name='live_activity_api'),
    path('user/<int:user_id>/actions/', user_actions_view, name='user_actions'),
    path('submit-ban-user/<int:user_id>/', submit_ban_user, name='submit-ban-user'),
    path('submit-ip-ban-user/<int:user_id>/', submit_ip_ban_user, name='submit-ip-ban-user'),
    path('edit-ad/<int:ad_id>/', edit_ad, name='edit-ad'),
    path('delete-ad/<int:ad_id>/', delete_ad, name='delete-ad'),
    path('add-ad/', add_ad, name='add-ad'),
    path('enable-feature/<int:feature_id>/', enable_feature, name='enable-feature'),
    path('enable-ad-feature/<int:feature_id>/', enable_ad_feature, name='enable-ad-feature'),
    path('maintenance-feature/<int:feature_id>/', maintenance_feature, name='maintenance-feature'),
    path('disable-feature/<int:feature_id>/', disable_feature, name='disable-feature'),
    path('disable-ad-feature/<int:feature_id>/', disable_ad_feature, name='disable-ad-feature'),
    path('vehicle-management/', vehicle_management, name='vehicle-management'),
    path('livery-management/', livery_management, name='livery-management'),
    path('livery-management/pending/', livery_approver, name='livery-approver'),
    path('vehicle-management/pending/', vehicle_approver, name='vehicle-approver'),
    path('edit-livery/<int:livery_id>/', edit_livery, name='edit-livery'),
    path('edit-vehicle/<int:vehicle_id>/', edit_vehicle, name='edit-vehicle'),
    path('delete-livery/<int:livery_id>/', delete_livery, name='delete-livery'),
    path('delete-vehicle/<int:vehicle_id>/', delete_vehicle, name='delete-vehicle'),
    path('replace-livery/', replace_livery, name='replace-livery'),
    path('replace-vehicle/', replace_vehicle, name='replace-vehicle'),
    path('publish-livery/<int:livery_id>/', publish_livery, name='publish-livery'),
    path('publish-vehicle/<int:vehicle_id>/', publish_vehicle, name='publish-vehicle'),
    path('flip-livery/', flip_livery, name='flip-livery'),
    path('applications-management/', applications_management, name='applications-management'),
    path("applications/<int:application_id>/", application_detail, name="application_detail"),
    path('restart-service/', restart_service, name='restart_service'),
    path('admin-site-links/', admin_site_links, name='admin-site-links'),
    path('forum-management/', forum_management_view, name='forum-management'),
    path('forum/resync-thread/<int:thread_id>/', resync_thread, name='resync-thread'),
    path('forum/resync-status/<int:thread_id>/', resync_status, name='resync-status'),
    path('forum/resync-pause/<int:thread_id>/', resync_pause, name='resync-pause'),
    path('forum/resync-resume/<int:thread_id>/', resync_resume, name='resync-resume'),
    path('forum/resync-stop/<int:thread_id>/', resync_stop, name='resync-stop'),
    path('forum/moderation/', forum_mod_threads, name='forum-mod-threads'),
    path('forum/moderation/thread/<int:thread_id>/', forum_mod_thread_detail, name='forum-mod-thread'),
    path('forum/moderation/thread/<int:thread_id>/delete/', mod_delete_thread, name='forum-mod-delete-thread'),
    path('forum/moderation/thread/<int:thread_id>/recreate/', mod_recreate_thread, name='forum-mod-recreate-thread'),
    path('forum/moderation/recreate-page/', mod_recreate_page, name='forum-mod-recreate-page'),
    path('forum/moderation/recreate-page-api/', mod_recreate_page_api, name='forum-mod-recreate-page-api'),
    path('forum/moderation/recreate-page-status/<str:task_id>/', recreate_page_status, name='forum-mod-recreate-page-status'),
    path('forum/moderation/post/<int:post_id>/delete/', mod_delete_post, name='forum-mod-delete-post'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)