# Generated by Django 5.2.3 on 2025-11-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='giveaway_prizes/'),
        ),
    ]
