# Generated by Django 5.2.3 on 2025-11-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0002_prize_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='tier',
            field=models.IntegerField(default=1),
        ),
    ]
