# Generated by Django 5.2.8 on 2025-12-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_historicaldaytype_historicalduty_historicaldutytrip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutytrip',
            name='inbound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldutytrip',
            name='inbound',
            field=models.BooleanField(default=True),
        ),
    ]
