# Generated by Django 5.2.8 on 2025-12-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_dutytrip_inbound_historicaldutytrip_inbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutytrip',
            name='snapped_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldutytrip',
            name='snapped_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
