# Generated by Django 5.2.3 on 2025-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_dutytrip_inbound_historicaldutytrip_inbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroutestop',
            name='snapped_route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='snapped_route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
