# Generated by Django 5.2.8 on 2025-12-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_dutytrip_snapped_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutytrip',
            name='snapped_route',
        ),
        migrations.RemoveField(
            model_name='historicaldutytrip',
            name='snapped_route',
        ),
        migrations.AddField(
            model_name='historicalroutestop',
            name='snapped_route',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='snapped_route',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
