# Generated by Django 5.2.3 on 2025-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_historicalroutestop_snapped_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroute',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
