# Generated by Django 5.2.8 on 2025-12-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_remove_dutytrip_snapped_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutytrip',
            name='end_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldutytrip',
            name='end_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
