# Generated by Django 5.2.8 on 2025-12-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_alter_dutytrip_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutytrip',
            name='end_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldutytrip',
            name='end_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalroutestop',
            name='snapped_route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='snapped_route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
