# Generated by Django 5.2.9 on 2025-12-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0039_alter_fleet_updated_at_and_more'),
        ('routes', '0017_duty_catagory_historicalduty_catagory_board_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board_category',
            options={'verbose_name_plural': 'Board Categories'},
        ),
        migrations.AlterModelOptions(
            name='historicalboard_category',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical board_category', 'verbose_name_plural': 'historical Board Categories'},
        ),
        migrations.RemoveField(
            model_name='duty',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='historicalduty',
            name='catagory',
        ),
        migrations.AddField(
            model_name='board_category',
            name='board_type',
            field=models.CharField(choices=[('duty', 'Duty'), ('running-boards', 'Running Board')], default='duty', max_length=20),
        ),
        migrations.AddField(
            model_name='board_category',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_categories', to='fleet.mbtoperator'),
        ),
        migrations.AddField(
            model_name='duty',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='routes.board_category'),
        ),
        migrations.AddField(
            model_name='historicalboard_category',
            name='board_type',
            field=models.CharField(choices=[('duty', 'Duty'), ('running-boards', 'Running Board')], default='duty', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalboard_category',
            name='operator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.mbtoperator'),
        ),
        migrations.AddField(
            model_name='historicalduty',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.board_category'),
        ),
    ]
