# Generated by Django 5.2.8 on 2025-11-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0033_historicalliverie_declined_liverie_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='order_by',
            field=models.CharField(choices=[('fleet_number', 'Fleet Number'), ('operator_name', 'Operator Name')], default='fleet_number', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='order_by',
            field=models.CharField(choices=[('fleet_number', 'Fleet Number'), ('operator_name', 'Operator Name')], default='fleet_number', max_length=20),
        ),
    ]
