# Generated by Django 5.2.3 on 2025-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_group_order_by_historicalgroup_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicletype',
            name='type_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='type_name',
            field=models.CharField(max_length=100),
        ),
    ]
