# Generated by Django 5.2.3 on 2025-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0035_alter_historicalvehicletype_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='sim_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='sim_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='sim_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='sim_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
