# Generated by Django 5.2.3 on 2025-12-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_fleet_sim_lat_fleet_sim_lon_historicalfleet_sim_lat_and_more'),
        ('tracking', '0010_historicaltrip_trip_inbound_trip_trip_inbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='current_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_current_trip', to='tracking.trip'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='sim_heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='current_trip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.trip'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='sim_heading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
