# Generated by Django 5.2.3 on 2025-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_fleet_current_trip_fleet_sim_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default="2000-01-01T00:00:00Z"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default="2000-01-01T00:00:00Z"),
            preserve_default=False,
        ),
    ]