# Generated by Django 5.2.3 on 2025-12-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0038_fleet_updated_at_historicalfleet_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
