# Generated by Django 5.2.9 on 2026-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0039_alter_fleet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmbtoperator',
            name='show_livery_border',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='show_livery_border',
            field=models.BooleanField(default=False),
        ),
    ]
