# Generated by Django 5.2.9 on 2026-01-11 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_historicalmbtoperator_show_livery_border_and_more'),
        ('routes', '0018_add_category_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_vehicle_category', to='routes.board_category'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.board_category'),
        ),
    ]
