# Generated by Django 5.2.9 on 2026-02-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0042_vehicle_type_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='sim_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='sim_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletypechangerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
