# Generated by Django 5.2.3 on 2025-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_stripesubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltheme',
            name='css',
            field=models.TextField(help_text='Upload a CSS file. <a href="https://cdn.mybustimes.cc/mybustimes/staticfiles/themes/templateTheme.css" target="_blank">Download template</a>', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(help_text='Upload a CSS file. <a href="https://cdn.mybustimes.cc/mybustimes/staticfiles/themes/templateTheme.css" target="_blank">Download template</a>', upload_to='themes/'),
        ),
    ]
