# Generated by Django 5.2.3 on 2025-12-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_historicaltheme_css_alter_theme_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltheme',
            name='css',
        ),
        migrations.RemoveField(
            model_name='historicaltheme',
            name='dark_theme',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='css',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='dark_theme',
        ),
        migrations.AddField(
            model_name='historicaltheme',
            name='dark_css',
            field=models.TextField(default=1, help_text='Upload a CSS file. <a href="https://cdn.mybustimes.cc/mybustimes/staticfiles/themes/templateTheme.css" target="_blank">Download template</a>', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltheme',
            name='light_css',
            field=models.TextField(default=1, help_text='Upload a CSS file. <a href="https://cdn.mybustimes.cc/mybustimes/staticfiles/themes/templateTheme.css" target="_blank">Download template</a>', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltheme',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='dark_css',
            field=models.FileField(default=1, help_text='Upload a CSS file. <a href="https://cdn.mybustimes.cc/mybustimes/staticfiles/themes/templateTheme.css" target="_blank">Download template</a>', upload_to='themes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='light_css',
            field=models.FileField(default=1, help_text='Upload a CSS file. <a href="https://cdn.mybustimes.cc/mybustimes/staticfiles/themes/templateTheme.css" target="_blank">Download template</a>', upload_to='themes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
