# Generated by Django 5.2.3 on 2025-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_historicaltheme_css_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltheme',
            name='main_colour',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='main_colour',
        ),
        migrations.AddField(
            model_name='historicaltheme',
            name='dark_main_colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltheme',
            name='light_main_colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='theme',
            name='dark_main_colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='theme',
            name='light_main_colour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
