# Generated by Django 5.2.3 on 2025-12-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_historicaltheme_main_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
