# Generated by Django 5.2.3 on 2025-12-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_customuser_dark_mode_historicalcustomuser_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltheme',
            name='sugggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='sugggested',
            field=models.BooleanField(default=False),
        ),
    ]
