# Generated by Django 5.2.8 on 2025-12-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_historicaltheme_sugggested_theme_sugggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='snap_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='snap_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
