# Generated by Django 5.2.3 on 2025-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_customuser_snap_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='snap_api_key',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='snap_api_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sub_plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='sub_plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free', max_length=10),
        ),
    ]
