# Generated by Django 5.2.3 on 2025-12-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_customuser_snap_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='sub_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=10),
        ),
    ]
