# Generated by Django 5.2.9 on 2025-12-26 12:26

from django.db import migrations

def migrate_bans(apps, schema_editor):
    BanType = apps.get_model('main', 'BanType')
    CustomUser = apps.get_model('main', 'CustomUser')

    # Create BanType rows
    forum_ban, _ = BanType.objects.get_or_create(name='forum')
    ticket_ban, _ = BanType.objects.get_or_create(name='ticket')
    messaging_ban, _ = BanType.objects.get_or_create(name='messaging')
    wiki_edit_ban, _ = BanType.objects.get_or_create(name='wiki_edit')

    # Iterate through users and migrate data
    for user in CustomUser.objects.all():
        if user.forum_banned:
            user.banned_from.add(forum_ban)
        if user.ticket_banned:
            user.banned_from.add(ticket_ban)
        if user.messaging_banned:
            user.banned_from.add(messaging_ban)
        if user.wiki_edit_banned:
            user.banned_from.add(wiki_edit_ban)

def reverse_migrate_bans(apps, schema_editor):
    CustomUser = apps.get_model('main', 'CustomUser')
    BanType = apps.get_model('main', 'BanType')

    forum_ban = BanType.objects.filter(name='forum').first()
    ticket_ban = BanType.objects.filter(name='ticket').first()
    messaging_ban = BanType.objects.filter(name='messaging').first()
    wiki_edit_ban = BanType.objects.filter(name='wiki_edit').first()

    for user in CustomUser.objects.all():
        user.forum_banned = False
        user.ticket_banned = False
        user.messaging_banned = False
        user.wiki_edit_banned = False

        if forum_ban and user.banned_from.filter(id=forum_ban.id).exists():
            user.forum_banned = True
        if ticket_ban and user.banned_from.filter(id=ticket_ban.id).exists():
            user.ticket_banned = True
        if messaging_ban and user.banned_from.filter(id=messaging_ban.id).exists():
            user.messaging_banned = True
        if wiki_edit_ban and user.banned_from.filter(id=wiki_edit_ban.id).exists():
            user.wiki_edit_banned = True
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_bantype_customuser_banned_from_historicalbantype'),
    ]

    operations = [
        migrations.RunPython(migrate_bans, reverse_migrate_bans),
    ]
