# Generated by Django 5.2.9 on 2025-12-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_migrate_ban_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='forum_banned',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='messaging_banned',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ticket_banned',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wiki_edit_banned',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='forum_banned',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='messaging_banned',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='ticket_banned',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='wiki_edit_banned',
        ),
    ]
