# Generated by Django 5.2.9 on 2025-12-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_customuser_forum_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='had_pro_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='had_pro_trial',
            field=models.BooleanField(default=False),
        ),
    ]
