# Generated by Django 5.2.9 on 2026-01-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_historicalcustomuser_last_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalactivesubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=100),
        ),
    ]
