# Generated by Django 5.2.9 on 2026-01-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_device_historicaldevice_historicaldeviceusage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregion',
            name='in_the',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='region_country',
            field=models.CharField(db_index=True, default='England', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='in_the',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_country',
            field=models.CharField(db_index=True, default='England', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
