# Generated by Django 5.2.8 on 2026-02-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_device_fingerprint_alter_device_first_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceusage',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deviceusage',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deviceusage',
            name='usage_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicaldeviceusage',
            name='first_seen',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaldeviceusage',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaldeviceusage',
            name='usage_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
