# Generated by Django 5.2.3 on 2025-12-02 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_historicaldaytype_historicalduty_historicaldutytrip_and_more'),
        ('tracking', '0008_historicaltracking_historicaltrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrip',
            name='trip_board',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.duty'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.duty'),
        ),
    ]
