# Generated by Django 5.2.3 on 2025-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_historicaltrip_trip_board_trip_trip_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrip',
            name='trip_inbound',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_inbound',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
