# Generated by Django 5.2.9 on 2026-01-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_other_team_tickettype_other_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltickettype',
            name='svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
